version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: is-docker
    versions:
    - 2.1.1
    - 2.2.0
  - dependency-name: qs
    versions:
    - 6.10.0
    - 6.9.6
  - dependency-name: boxen
    versions:
    - 5.0.0
  - dependency-name: p-timeout
    versions:
    - 4.1.0
  - dependency-name: get-stream
    versions:
    - 6.0.0
  - dependency-name: chalk
    versions:
    - 4.1.0
